updated_at: 11:00AM
url: "https://cybersecrs.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Colorchain # the name of your site, e.g. ACME Corp.
author: Colorchain
description: Colorchain Cryptocurrency Rates

sass:
  sass_dir: css
  style:    compressed
